### ISSUE TITLE
Proteus PNP footprint and connector

### ISSUE THREAD

**Issue by OrchardPerformance** [rusefi/kicad-libraries#16]
If we are going to base some PNP boards on the Proteus then we need to produce a master footprint for the Proteus board like we have for the MRE. 
We also need to decide on a suitable way to couple the Proteus to the PNP adapter board, a quick check shows the pins are about 4mm spacing. It looks like 3.96mm is a standard header spacing, something off the shelf may exist. 
@rusefi @jharvey @mck1117

**Comment by rusefi** [comment]
I totally forgot that we already have first Proteus PNP board by @CrazyStriker

**Comment by rusefillc** [comment]
@jharvey I believe we have pushed something had we?

**Comment by rusefillc** [comment]
@Qwerty-OFF we have a great Proteus PNP footprint and connector, where is it persisted?

**Comment by Qwerty-OFF** [comment]
[Kicad6-libraries](https://github.com/rusefi/kicad6-libraries)
